### ISSUE TITLE
require("../request/request-client.js") 인식 안됨

### ISSUE THREAD

**Issue by Abell-Choi** [naijun0403/kakaolink#7]
채팅자동응답봇 베타 5
카카오링크 3.6버전을 사용중에 있습니다.

src/modules/service/kakao-api-service.js 내부의 
const {RequestClient} = require("../request/request-client.js");
코드에서 문제가 발생하였습니다.

코드를 다른곳에 이동 후 require의 경로를 다시 잡아봤는데도 똑같았습니다.
혹시 다른 해결방법이 있습니까?

**Comment by naijun0403** [comment]
채자봇 용 따로 만들었습니다 (1.0.8)
